### ISSUE TITLE
Dev scripts

### ISSUE THREAD

**Issue by mhmdtshref** [founders-programme-2/howl#104]
https://github.com/founders-programme-2/howl/blob/b8853dba9e6a17add2bc01b3dc14b6fe24e0ad93/package.json#L7-L9

I think it's better to have `dev:server` script that runs express server using nodemon. Also we need a script `dev:client` which runs `cd client && npm start` which runs the react app in development mode.

What do you think guys?

**Comment by teenie-quaggard** [comment]
i am happy with that 👍

it could also be good just to set up a proxy so we only have to run one script? up for discussion.

**Comment by mhmdtshref** [comment]
## My suggestion:

```
"dev:client": " "cd client  && npm start",
"dev:server": "nodemon ./src/server.js"
```

**Comment by orjwan98** [comment]
@mhmdtshref go for it :D
