### ISSUE TITLE
Research: Uploading Images to Airtable

### ISSUE THREAD

**Issue by Oliversw** [founders-programme-2/howl#13]
[From this link:](https://chinarajames.com/how-to-upload-images-to-airtable-using-their-api/)
Airtable doesn’t allow you to directly upload images via their api. They do, however, allow you to pass an object of attachments urls. This, however, means that the images need to be on a web server and therefore won’t work from local development environment.

**Comment by Oliversw** [comment]
I think that link is actually going to be very useful.

They use 3 things:
1.  middleware on express that handles the actual picture
2. Cloudinary, a hosting platform that has a pretty good free tier that I think we can use
3. Airtable, to send the stored picture links to

**Comment by teenie-quaggard** [comment]
Relates to #29
