### ISSUE TITLE
As a user, I want a clear understanding of how to navigate the website

### ISSUE THREAD

**Issue by teenie-quaggard** [founders-programme-2/howl#19]
Relates to #18 

- [x] Information page on how to use the site
- [x] Linked to main page

Includes:
- [x] Links to all pages (contribute, main, howl/mission statement, wlm brief, resources)
- [x] Includes information on how to search / use filtering tools of timeline 
- [x] Information on how to add contribute

**Comment by Oliversw** [comment]
Sorry to be leaving questions everywhere, but is this intended to be separate from the introduction modal? I'm not sure where we might want to place this

Thank youuu

**Comment by teenie-quaggard** [comment]
@Oliversw so this is the ```need help``` button in the timeline controls. 
i think we need it in case what we have done in terms of filtering/searching is not clear to an older person.
