### ISSUE TITLE
Stack

### ISSUE THREAD

**Issue by teenie-quaggard** [founders-programme-2/howl#2]
Proposed:

React
Styled Components
Material UI
Airtable
Jest

Desktop first design

Heroku
Travis
Codecov
Imgbot
Accesslint

**Comment by teenie-quaggard** [comment]
@founders-programme-2/howl 

Hey everyone, Oliver and I have been thinking that this project might be a good one to try D3, a data visualization library. I've heard a lot about it, but was wary to introduce something that seemed difficult. That said, I met a woman at a React conference on Friday that said that it really isn't too difficult (in her words, 'just another library') and that working in D3 would really help develop our employable skills. 

I'd really like to try, but it is something to discuss as a team, as we will have to schedule in a technical spike.

https://d3js.org/

**Comment by teenie-quaggard** [comment]
Also - for accessibility: https://github.com/dequelabs/react-axe

**Comment by mhmdtshref** [comment]
About data visualization, there's another good and easy library called [CanvasJS](https://canvasjs.com/).
I think we should compare them together to pick the best library for the project.

**Comment by teenie-quaggard** [comment]
@mhmdtshref - yes it's always good to look at different options! thanks for sending the link :)

@founders-programme-2/howl i just watched this talk on react / d3 and the live coding segment really opened my eyes to how the two would interact! it's definitely worth a watch :)

**Comment by teenie-quaggard** [comment]
@founders-programme-2/howl  there is also this library build by formidable!
it is basically d3 that has been rebuilt for use with react. looks pretty cool!
sorry for the overload of choices - i feel like this is a good thread to throw everything that we find, and we can talk through them on Tuesday :)

https://formidable.com/open-source/victory/
https://www.youtube.com/watch?v=n8TwLWsR40Y

**Comment by Oliversw** [comment]
https://github.com/pixijs/pixi.js There's always the framework that histography.io is built on too
