### ISSUE TITLE
Add loading sign/word before [/archive/feed] and [/story/:id] being loaded. PR #206

### ISSUE THREAD

**Issue by mhmdtshref** [founders-programme-2/howl#204]
Here on this page, when clicking on the archive page, we have to wait a short time with a page like this below until stories being downloaded.

So we have to add a  loading sign or word, shown until the stories being loaded.

<img width="1994" alt="Screen Shot 2019-05-27 at 11 34 37 AM" src="https://user-images.githubusercontent.com/19406147/58406977-7429c680-8073-11e9-9a03-9794fe6edc6a.png">

**Comment by orjwan98** [comment]
Same thing for `/story/:id`.
