### ISSUE TITLE
Page - on load modal component

### ISSUE THREAD

**Issue by teenie-quaggard** [founders-programme-2/howl#36]
Relates to: #24 #25 #26 

Includes:

- [ ] logo
- [ ] intro to Howl (link to extensive)
- [ ] main goals of project 
- [ ] quick summary of WLM (link to extensive)
- [ ] button to close modal / see main page

- [ ] should not scroll

**Comment by Oliversw** [comment]
Have the HOWL women written anything that they would like for the intro yet?

**Comment by Oliversw** [comment]
Material UI has some great, accessible modals! https://material-ui.com/demos/dialogs/

**Comment by teenie-quaggard** [comment]
@Oliversw - I don't think so! I think I forgot to tell them at the last workshop. I will send a message.
and good find on the modals :)

**Comment by teenie-quaggard** [comment]
Replaced by /main page
