### ISSUE TITLE
Make all dummy pages & route

### ISSUE THREAD

**Issue by teenie-quaggard** [founders-programme-2/howl#58]
- [x] timeline
- [x] individual story entry (maybe hard coded entry for now, will eventually be dynamically added)
- [x] about
- [x] women's liberation movement
- [x] resources
- [x] archive landing page
- [x] archive search result page
- [x] add your story page
- [x] help page

**Comment by orjwan98** [comment]
@teenie-quaggard can you explain the difference between number 2 and number 8? I don't quite understand what number 2 is. :/

**Comment by teenie-quaggard** [comment]
Number two is where you would view an individual story that you clicked on from the timeline or through the search function in the archive

![Screen Shot 2019-05-11 at 17 48 04](https://user-images.githubusercontent.com/37771591/57572636-0b0c4700-7415-11e9-8863-a0234462ae55.png)

Add your story is the form and the rules of posting :)

@orjwan98
