### ISSUE TITLE
Create global react theme for project styling

### ISSUE THREAD

**Issue by teenie-quaggard** [founders-programme-2/howl#59]

**Comment by Oliversw** [comment]
Would this be in the form of a styled components theme?

**Comment by teenie-quaggard** [comment]
yes as in:
https://www.youtube.com/watch?v=DL4HAKo76Cw

**Comment by mhmdtshref** [comment]
We also can create a css file `client/public/index.css` and call it on the html react main `file/client/public/index.html`, what do you think @teenie-quaggard ?

**Comment by teenie-quaggard** [comment]
@mhmdtshref that true too!

But if we are using styled components, I feel like it’s better practice to use one kind of stying :)

**Comment by mhmdtshref** [comment]
I think we don't need to import it many times, just one time at the `App` component is enough, right?
