### ISSUE TITLE
Initial braindump - User Stories & Journeys 

### ISSUE THREAD

**Issue by teenie-quaggard** [founders-programme-2/howl#6]
## Main Technical goals

- Capture content from a form & send that data to be stored in an airtable database
- Content must be approved in airtable before it goes public

- Timeline is prepopulated with some data / important dates
- When content from the form is approved, it is displayed on a timeline as a dot
- Dot is color mapped by main category
- Dot can be hovered for small animation, title 'snapshot' and clicked on for more information (modal)
- Search function allows user to visually filter by category, type of material, tags, date

## User Journeys

- As a user, I want to be able to share my story and historical artifacts so that I can contribute to society's understanding of the Women's Liberation Movement
- As a user, I want to learn and become engaged with history in a way that makes me passionate about the present day
- As a user, I want history to be presented in an engaging way

### Accessibility
- As a user, I want to follow GDPR guidelines
- As a user, I want an easy to navigate webpage
- As a user, I want this site to be accessible to people of all abilities
- As a user, I want a way of moderating content before it is posted publically
- As a user, I want to be clear about copyright laws

### Content
- As a user, I want to be felt accepted by the platform, even if some of my views conflict with views held by other stories in the archive
- As a user, I want a brief description of who Howl is
- As a user, I want to understand the goals of the project
- As a user, I want a brief description of the Women's Liberation Movement
- As a user, I want the rules of adding to the archive to be clear
- As a user I want to be able to upload a story, an image, an event
- As a user I want to be able to see my story on a timeline in relation to other events
- As a user, I want a way of searching / filtering content through categories and tagging
    - Color categorisation

### Outreach
- As a user, I want to be able to recommend this site to another friend

## Stretch goals
- As a user, I want to be provided with related resources
    - Archives
    - Music
    - Book lists
    - Women's centers
    - Art
- As a user, I want to view this website on a mobile phone
- As a user, I want to view this site on a tablet
- As a user, I want to be able to donate to HOWL
- As a user, I want to log in so that I can edit my posts or delete them
- As a user, I want to be able to comment on posts

## Pages
- Main timeline page 
    - Search function
        - by keyword
        - by tag
        - by year
        - by category
        - by format
        - by random 
- Add to timeline page
    - GDPR stuff
    - Rules of posting
    - Form
        - Contact information
        - Relationship to WLM
        - Text
        - Upload media files
        - Categorization of material
        - Tagging of content
        - Date
        - Related evidence (links, books) if possible

**Comment by Oliversw** [comment]
This is fantastic, thanks Kristina! I especially love that you have baked accessibility into the user stories 🎉

**Comment by teenie-quaggard** [comment]
# User Journey:
## As a user, I/we need to organize & collect my/our memories in an easy to understand way so that I/we can pass on my/our history to other people


![image1](https://user-images.githubusercontent.com/37771591/57307305-3bce4280-70dc-11e9-8000-77002bf952ed.jpeg)
![image2](https://user-images.githubusercontent.com/37771591/57307306-3c66d900-70dc-11e9-9371-cffc38a200b9.jpeg)

**Comment by teenie-quaggard** [comment]
See new issue #33
