### ISSUE TITLE
Finalise decision on stack

### ISSUE THREAD

**Issue by teenie-quaggard** [founders-programme-2/howl#60]

**Comment by Oliversw** [comment]
Is this regarding things like d3?

**Comment by Oliversw** [comment]
If we use the information that I found about uploading images, we might have to include the image hosting service Cloudinary in our stack. Just a note!

**Comment by teenie-quaggard** [comment]
@Oliversw yes - d3 or other library
victory is the one I was talking about in the meeting
it's made with d3 for react
https://formidable.com/open-source/victory/
