### ISSUE TITLE
Decide on airtable columns and build the database schema

### ISSUE THREAD

**Issue by teenie-quaggard** [founders-programme-2/howl#63]
- [x] set up Airtable account
- [x] Build basic database schema
- [x] Input some dummy data to test

**Comment by mhmdtshref** [comment]
I think this is the schema we need for now:

| ID | Owner | Title | Story text |
|----|-------|-------|------------|
|    |       |       |            |
|    |       |       |            |
|    |       |       |            |

**Comment by teenie-quaggard** [comment]
What about date?

There’s also going to be a bunch of other form entries. Including photos etc. 

Should we just get started on the basics and then add more later?

**Comment by teenie-quaggard** [comment]
What about:

For stories, which will be the first milestone:

| ID | Contact-Name | Contact-Email | Contact-Number | Type | Date | Location | Category | Story-Text | Relationship-WLM | Event | Tags | Status |

**Comment by orjwan98** [comment]
@founders-programme-2/howl 

![image](https://user-images.githubusercontent.com/41706997/57569725-d3e06a80-7401-11e9-9296-7ee538147e69.png)

Tables: **1 table only - posts**

Fields types:

**id - autonumber** - automatically increments count and generates a unique number for each record. 
**owner - single line text**
**title - multi-line text**
**body - multi-line text**
**date - date**
**status - checkbox**

**Comment by teenie-quaggard** [comment]
Looks great! Thank you!!!! Feel free to close the issue :)
